[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm build"

[deploy]
startCommand = "pnpm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.healthcheckPath]
path = "/"
