CREATE TABLE `concrete_cubes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`groupId` int NOT NULL,
	`markNo` int NOT NULL,
	`cubeId` varchar(64),
	`dateTested` timestamp,
	`length` decimal(8,2) DEFAULT '150',
	`width` decimal(8,2) DEFAULT '150',
	`height` decimal(8,2) DEFAULT '150',
	`massKg` decimal(8,3),
	`maxLoadKN` decimal(10,3),
	`fractureType` varchar(16),
	`densityKgM3` decimal(10,2),
	`compressiveStrengthMpa` decimal(10,3),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `concrete_cubes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `concrete_test_groups` (
	`id` int AUTO_INCREMENT NOT NULL,
	`distributionId` int NOT NULL,
	`sampleId` int NOT NULL,
	`technicianId` int NOT NULL,
	`testAge` int NOT NULL,
	`contractNo` varchar(128),
	`projectName` varchar(256),
	`contractorName` varchar(256),
	`location` varchar(256),
	`region` varchar(128),
	`consultant` varchar(256),
	`cscRef` varchar(128),
	`placeOfSampling` varchar(256),
	`sourceSupplier` varchar(256),
	`batchDateTime` varchar(128),
	`slump` varchar(64),
	`classOfConcrete` varchar(128),
	`maxAggSize` varchar(64),
	`nominalCubeSize` varchar(64) DEFAULT '150mm',
	`methodOfCompaction` varchar(128) DEFAULT 'Using Compacting Bar',
	`appearance` varchar(128) DEFAULT 'Normal',
	`dateSampled` timestamp,
	`sampledBy` varchar(128) DEFAULT 'Contractor',
	`curingMethod` varchar(256) DEFAULT 'BS 1881 Part 111: 1983',
	`moistureCondition` varchar(128) DEFAULT 'Saturated',
	`removalOfFins` varchar(128) DEFAULT 'Using Steel File',
	`volumeDetermination` varchar(128) DEFAULT 'By Calculation',
	`testedBy` varchar(128),
	`comments` text,
	`avgCompressiveStrength` decimal(10,3),
	`minAcceptable` decimal(10,3),
	`maxAcceptable` decimal(10,3),
	`complianceStatus` enum('pass','fail','partial'),
	`status` enum('draft','submitted','approved','rejected','revision_requested') NOT NULL DEFAULT 'draft',
	`submittedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `concrete_test_groups_id` PRIMARY KEY(`id`)
);
