CREATE TABLE `clearance_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`requestCode` varchar(32) NOT NULL,
	`contractId` int NOT NULL,
	`contractorId` int NOT NULL,
	`contractNumber` varchar(128) NOT NULL,
	`contractName` varchar(512),
	`contractorName` varchar(256) NOT NULL,
	`requestedById` int NOT NULL,
	`totalTests` int NOT NULL DEFAULT 0,
	`passedTests` int NOT NULL DEFAULT 0,
	`failedTests` int NOT NULL DEFAULT 0,
	`pendingTests` int NOT NULL DEFAULT 0,
	`totalAmount` varchar(32) NOT NULL DEFAULT '0.00',
	`inventoryData` json,
	`paymentOrderNumber` varchar(64),
	`paymentOrderDate` timestamp,
	`paymentOrderIssuedById` int,
	`paymentOrderPdfUrl` text,
	`contractorLetterUrl` text,
	`sectorLetterUrl` text,
	`paymentReceiptUrl` text,
	`testListUrl` text,
	`certificateCode` varchar(32),
	`certificatePdfUrl` text,
	`certificateIssuedAt` timestamp,
	`status` enum('pending','inventory_ready','payment_ordered','docs_uploaded','issued','rejected') NOT NULL DEFAULT 'pending',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `clearance_requests_id` PRIMARY KEY(`id`),
	CONSTRAINT `clearance_requests_requestCode_unique` UNIQUE(`requestCode`)
);
